sudo: false
language: java
cache:
  directories:
  - $HOME/.m2
arch:
  - amd64
  - arm64
before_install:
  - sudo apt-get -y install openjdk-9-jdk
  - export JAVA_HOME=/usr/lib/jvm/java-9-openjdk-arm64/
install: true
script:
  - mvn clean test -Dmaven.test.redirectTestOutputToFile=true -P travis
  - mvn jacoco:report -P travis
branches:
  only:
  - develop
jdk:
  - openjdk9

after_success:
  - bash <(curl -s https://codecov.io/bash)
